# 데이터 전처리

- 결손값 - NaN, Null 변환 > 평균값 또는 드롭, 중요도 고려
- 사이킷런 머신러닝 알고리즘은 문자열 값 입력값으로 허용 안함
    - 모든 문자열 값은 인코딩돼서 숫자 형식으로 변환해야 함
    - 문자열 피처 = 카테고리형, 텍스트형 피처 의미 
        - 카테고리형 피처 = 코드 값으로 표현
        - 텍스트형 피처 = 피처 벡터화, 삭제


## 데이터 인코딩

- 레이블 인코딩, 원핫 인코딩

- 레이블 인코딩(Label encoding)
    - 카테고리 피처를 코드형 숫자 값으로 변환하는 것


### 레이블 인코딩

- LabelEncoder 클래스로 구현 
    - LabelEncoder 를 객체로 생성한 후 fit() 과 transform() 호출해 레이블 인코딩 수행 

In [4]:
from sklearn.preprocessing import LabelEncoder 

items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

# LabelEncoder 를 객체로 생성한 후, fit() 과 transform() 으로 레이블 인코딩 수행

encoder = LabelEncoder()
encoder.fit(items) 
labels = encoder.transform(items) 

print('인코딩 변환값: ', labels) 

# 문자열 값이 어떤 숫자 값으로 인코딩 됐는지 직관적으로 알고 싶으면 LabelEncoder 객체의 classes_ 속성값으로 확인
print('인코딩 클래스: ', encoder.classes_)

# inverse_transform() 인코딩 > 다시 디코딩
print('디코딩 원본값: ', encoder.inverse_transform([4, 5, 2, 0, 1, 1, 3, 3,]))


# 레이블 인코딩은 숫자 값의 크고작은 특성으로 예측 성능이 떨어질 수 있음

인코딩 변환값:  [0 1 4 5 3 3 2 2]
인코딩 클래스:  ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']
디코딩 원본값:  ['전자레인지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


### 원 핫 인코딩(one-hot Encoding) 

- 피처 값의 유형에 따라 새로운 피처를 추가해 고유 값에 해당하는 칼럼에만 1을 표시하고 나머지 컬럼에 0을 표시

- 사이킷런 OneHotEncoder 클래스.
   - 주의: 입력값으로 2차원 데이터 필요
   - 변환값이 희소행렬(Sparse Matrix) 형태므로 다시 toarray() 메서드 이용해 밀집행렬(Dense Matrix) 변환.

In [7]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items=['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

# 2차원 ndarray로 변환합니다. 
items = np.array(items).reshape(-1, 1)

# 원-핫 인코딩을 적용합니다. 
oh_encoder = OneHotEncoder()
oh_encoder.fit(items)
oh_labels = oh_encoder.transform(items)

# OneHotEncoder로 변환한 결과는 희소행렬이므로 toarray()를 이용해 밀집 행렬로 변환. 
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


In [11]:
# 판다스 원-핫 인코딩 지원 API get_dummies() 
# 문자열 카테고리 값을 숫자 형으로 변환할 필요 없이 바로 변환 가능
import pandas as pd

df = pd.DataFrame({'items':['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']})
pd.get_dummies(df) 

items_TV  items_냉장고  items_믹서  items_선풍기  items_전자레인지  items_컴퓨터
0         1          0         0          0            0          0
1         0          1         0          0            0          0
2         0          0         0          0            1          0
3         0          0         0          0            0          1
4         0          0         0          1            0          0
5         0          0         0          1            0          0
6         0          0         1          0            0          0
7         0          0         1          0            0          0

### 피처 스케일링과 정규화

- 피처스케일링(feature scaling): 서로 다른 변수의 값 범위를 일정한 수준으로 맞추는 작업

    - 표준화(Standardization), 정규화(Normalization) 
        - 표준화: 데이터 피처 각각 평균 0, 분산 1인 가우시안 정규 분포 가진 값으로 변환
            - 표준화 변환 피처 x 새로운 i 번째 데이터 x_new 면
            - 원래 값에서 피처 x 평균을 뺀 값을 피처 x 표준편차로 나눈 값

    - 정규화: 서로 다른 피처 크기를 통일하기 위해 크기를 변환
        - 최소 0 ~ 최대 1 값으로 변환
        - 개별 데이터 크기를 모두 똑같은 단위로 변경
        - 새로운 데이터 x_new 는 원래 값에서 피처 x 의 최솟값을 뺀 값을 피처 x의 최댓값과 최솟값 차이로 나눈 값
        - 사이킷런 Normalizer 모듈과 일반적인 정규화는 약간 차이
            - 일반 표준화,정규화 = 피처 스케일링
            - 선형대수 개념 정규화 = 벡터 정규화

- 사이킷런 피처 스케일링 클래스: StandardScaler , MinMaxScaler            

#### StandardScaler 

- 표준화 지원 클래스
- 개별 피처를 평균 0, 분산 1 값으로 변환
- 가우시안 정규분포
- 서포트 벡터 머신(Support Vector Machine), 선형 회귀(Linear Regressor), 로지스틱 회귀(Logistic Regression) 
    - 데이터가 가우시안 정규분포 가정하고 구현해서 사전에 표준화 적용은 예측 성능 향상에 중요한 요소

In [12]:
from sklearn.datasets import load_iris
import pandas as pd
# 붓꽃 데이터 셋을 로딩하고 DataFrame으로 변환합니다. 
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

# 데이터 세트 확인
print('feature 들의 평균 값')
print(iris_df.mean())
print('\nfeature 들의 분산 값')
print(iris_df.var())

feature 들의 평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature 들의 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [13]:
# StandardScaler 이용해 각 피처 한 번에 표준화하기
# StandardScaler 객체 생성 - fit()과 transform() 메서드에 변환 대상 피처 데이터 세트 입력하고 호출하면 변환
# transform() 호출할 때 스케일 변환된 데이터 세트가 넘파이의 ndarray 이므로 DataFarme 으로 변환해 평균값과 분산 값을 다시 확인

from sklearn.preprocessing import StandardScaler

# StandardScaler객체 생성
scaler = StandardScaler()
# StandardScaler 로 데이터 셋 변환. fit( ) 과 transform( ) 호출.  
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

#transform( )시 scale 변환된 데이터 셋이 numpy ndarry로 반환되어 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature 들의 평균 값')
print(iris_df_scaled.mean())
print('\nfeature 들의 분산 값')
print(iris_df_scaled.var())

feature 들의 평균 값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

feature 들의 분산 값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


#### MinMaxScler

- 데이터값을 0과 1사이 범위 값으로 변환(음수값 있으면 -1 ~ 1 값으로 변환) 
- 데이터 분포가 가우시안 분포가 아닌 경우 Min, Max scale 적용 가능

In [14]:
from sklearn.preprocessing import MinMaxScaler

# MinMaxScaler객체 생성
scaler = MinMaxScaler()
# MinMaxScaler 로 데이터 셋 변환. fit() 과 transform() 호출.  
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

# transform()시 scale 변환된 데이터 셋이 numpy ndarry로 반환되어 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature들의 최솟값')
print(iris_df_scaled.min())
print('\nfeature들의 최댓값')
print(iris_df_scaled.max())

feature들의 최솟값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

feature들의 최댓값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


#### 학습 데이터와 테스트 데이터 스케일링 변환 시 유의점

- 스케일링 변환 시 fit(), transform(), fit_transform() 메서드 이용
- fit() : 데이터 변환을 위한 기준 정보 설정(예, 데이터 세트 최댓값/최솟값 설정 등) 적용
- transform() : 설정된 정보를 이용해 데이터 변환
- fit_transform() : fit() 과 transform() 을 한 번에 적용

- 학습 데이터 세트와 테스트 데이터 세트에 fit() 과 transform() 적용 시 주의 필요
    - Scaler 객체 이용 학습데이터 세트로 fit()과 transform() 적용하면 테스트 데이터 세트로는 다시 fit() 수행하지 않고 학습 데이터 세트로 fit()을 수행한 
      결과를 이용해 transform() 변환을 적용해야 한다는 것 
    - 즉, 학습 데이터로 fit()이 적용된 스케일링 기준 정보를 그대로 테스트 데이터에 적용해야 하며, 그렇지 않고 테스트 데이터로 다시 새로운 스케일링 기준 정보
      를 만들게 되면 학습 데이터와 테스트 데이터의 스케일링 기준 정보가 달라져 올바른 예측 결과를 도출하지 못할 수도

In [15]:
# 테스트 데이터에 fit()을 적용할 때 문제 보기
# np.arange() 이용 학습데이터를 0 ~ 10까지, 테스트 데이터를 0 ~ 5까지 가지는 ndarray 생성

from sklearn.preprocessing import MinMaxScaler
import numpy as np

# 학습 데이터는 0 부터 10까지, 테스트 데이터는 0 부터 5까지 값을 가지는 데이터 세트로 생성
# Scaler클래스의 fit(), transform()은 2차원 이상 데이터만 가능하므로 reshape(-1, 1)로 차원 변경
train_array = np.arange(0, 11).reshape(-1, 1)
test_array =  np.arange(0, 6).reshape(-1, 1)

In [16]:
# MinMaxScaler 객체에 별도의 feature_range 파라미터 값을 지정하지 않으면 0~1 값으로 변환
scaler = MinMaxScaler()

# fit()하게 되면 train_array 데이터의 최솟값이 0, 최댓값이 10으로 설정.
scaler.fit(train_array)

# 1/10 scale로 train_array 데이터 변환함. 원본 10-> 1로 변환됨.
train_scaled = scaler.transform(train_array)

print('원본 train_array 데이터:', np.round(train_array.reshape(-1), 2))
print('Scale된 train_array 데이터:', np.round(train_scaled.reshape(-1), 2))

원본 train_array 데이터: [ 0  1  2  3  4  5  6  7  8  9 10]
Scale된 train_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [17]:
# MinMaxScaler에 test_array를 fit()하게 되면 원본 데이터의 최솟값이 0, 최댓값이 5로 설정됨
scaler.fit(test_array)

# 1/5 scale로 test_array 데이터 변환함. 원본 5->1로 변환.
test_scaled = scaler.transform(test_array)

# test_array의 scale 변환 출력.
print('원본 test_array 데이터:', np.round(test_array.reshape(-1), 2))
print('Scale된 test_array 데이터:', np.round(test_scaled.reshape(-1), 2))

원본 test_array 데이터: [0 1 2 3 4 5]
Scale된 test_array 데이터: [0.  0.2 0.4 0.6 0.8 1. ]


In [18]:
scaler = MinMaxScaler()
scaler.fit(train_array)
train_scaled = scaler.transform(train_array)
print('원본 train_array 데이터:', np.round(train_array.reshape(-1), 2))
print('Scale된 train_array 데이터:', np.round(train_scaled.reshape(-1), 2))

# test_array에 Scale 변환을 할 때는 반드시 fit()을 호출하지 않고 transform() 만으로 변환해야 함. 
test_scaled = scaler.transform(test_array)
print('\n원본 test_array 데이터:', np.round(test_array.reshape(-1), 2))
print('Scale된 test_array 데이터:', np.round(test_scaled.reshape(-1), 2))

원본 train_array 데이터: [ 0  1  2  3  4  5  6  7  8  9 10]
Scale된 train_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

원본 test_array 데이터: [0 1 2 3 4 5]
Scale된 test_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5]


fit_transform() 적용은 학습데이터는 상관없지만 테스트데이터 에서는 절대 사용해선 안된다.

따라서, 학습과 테스트데이터 세트로 분리하기 전에 전체 데이터 세트에 스케일링 적용한 뒤 학습과 테스트 데이터 세트로 분리하는 것이 바람직.

* 유의점 정리
1. 가능하면 전체 데이터의 스케일링 변환을 적용한 뒤 학습과 테스트 데이터 분리
2. 1이 여의치 않다면 테스트 데이터 변환 시에는 fit()이나 fit_transform() 을 적용하지 않고 학습 데이터로 이미 fit() 된 Scaler 객체를 이용 transform() 변환